export const eventActionsTypes = {
    FETCH_EVENTS: "FETCH_EVENTS",
    SELECTED_EVENT: "SELECTED_EVENT",
    REMOVE_SELECTED_EVENT: "REMOVE_SELECTED_EVENT",
    ERROR:"ERROR",

    EVENTS_CREATE_REQUEST: "EVENTS_CREATE_REQUEST",
    EVENTS_CREATE_SUCCESS: "EVENTS_CREATE_SUCCESS",
    EVENTS_CREATE_FAIL: "EVENTS_CREATE_FAIL",

    EVENTS_UPDATE_REQUEST: "EVENTS_UPDATE_REQUEST",
    EVENTS_UPDATE_SUCCESS: "EVENTS_UPDATE_SUCCESS",
    EVENTS_UPDATE_FAIL: "EVENTS_UPDATE_FAIL",

    EVENTS_DELETE_REQUEST: "EVENTS_DELETE_REQUEST",
    EVENTS_DELETE_SUCCESS: "EVENTS_DELETE_SUCCESS",
    EVENTS_DELETE_FAIL: "EVENTS_DELETE_FAIL",

    COMMENT:'COMMENT',

};

