export const ActionsTypes = {
    SET_PROJECTS: "SET_PROJECTS",
    SELECTED_PROJECT: "SELECTED_PEOJECT",
    REMOVE_SELECTED_PROJECT: "REMOVE_SELECTED_PEOJECT",
    SET_TASKS: "SET_TASKS",
    SELECTED_TASK: "ELECTED_TASK",
    REMOVE_SELECTED_TASK: "REMOVE_SELECTED_TASK",
};
